package mageswaran.unit4;

/**
 * ObjectHeight.java
 * This program is to print 2 methods in a main
 * December 16, 2019
 * @author Mathen M
 */

public class MethodTesting {

	/**Entry point to this program.
	 * @param args unused
	 */
	
	public static void printSignature() {
		{
 System.out.println(" _____ ______   ________  _________  ___  ___  _______   ________ "     
					"|\   _ \  _   \|\   __  \|\___   ___\\  \|\  \|\  ___ \ |\   ___  \"    
					"\ \  \\\__\ \  \ \  \|\  \|___ \  \_\ \  \\\  \ \   __/|\ \  \\ \  \"   
					 "\ \  \\|__| \  \ \   __  \   \ \  \ \ \   __  \ \  \_|/_\ \  \\ \  \"  
					  "\ \  \    \ \  \ \  \ \  \   \ \  \ \ \  \ \  \ \  \_|\ \ \  \\ \  \"
					   "\ \__\    \ \__\ \__\ \__\   \ \__\ \ \__\ \__\ \_______\ \__\\ \__\"
					    "\|__|     \|__|\|__|\|__|    \|__|  \|__|\|__|\|_______|\|__| \|__|");
		}
		
	public static void printArt() {
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWWMWN0OKNNWWWMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNOl:colloddk0XWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWW0o:d0XX0Okkddolllox0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMXdcl0NWWWWWWWWWWXK0kdollldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkclxKWWX0KWWWWMMMMMMMMWXKkdllldx0XWWWWWWWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWKl:d0KKN0c:OWWMMMMMMMMMMWWMMWNK0kdlclodx0NWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNk:cOKKXNO::OWWWMMMMMMMMMMMMMMMWWWWWNXOkdlccdOXNWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:oO0XNWKc:OWWWWWMMMMMMMMMMMMMMMMMWWWWWMMNXOoccldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNkccx00NWWNd;xWWWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOdc:cokKNWWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKl:dO0XWWWNk;oXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0xlcclxKWWWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:lk0KNWWWNO:cKWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKkoc:o0NMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWWWKo:oOKXWWWWWKc;OWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWX0xlclkNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWNk::xKXWWWMWWXd;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMNX0OdccONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXo;o0XNWWWMMWWO:lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK00d:l0WMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0c:xKWWWMMMWMWXl;OWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWX00Oc:kNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk::ONWWWWMMWWMNk:oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK00o;dXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWXx;l0NWWMMMMMMMMKcc0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMWWWWXK0x:l0NWWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWW0l:dXWMWMMMMMMMMWd;xWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMWWWNNXNNK0d;oXMWWMWWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:cONWWWMMMMMMMMMKc:KWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNK000OOO0K00k:;kNNWMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l;dXWWWMMMMMMMMMMWk;dNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK00Okdollllcllllllccll:;clllldO0KXKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXx:cONMMMMMMMMMMMWMMNo,kWWWWWMMMMMMMMMMMMWMMMMMWWWMMMWNX0OxddoooooddxkkkkO0KKXXXNNNNNNNXKKK0kxolccc;'ckXWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWKl:dXWMMMMMMMMMMMMMMMNl;OMMMWWMMMMMMMMMMWWWWWWWWWNKOxolcc:cllodkO0XNNNNWNNNWWNNNNNNNNNNNNNWWWWMWWNXKOo;,:xKWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNk::ONMWWMMMMMMMMMMWWMW0c:KMMWWMMMMMMMMMMWWMWWWXOdolcclodxO0KXXXNNNWNNNNWWWWWWWWWWWMMWWWWNXXNNNNNWWWWMWWKo,'cONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd:oKWMWWWMMMMMMMMMWWWKxl;oXMWWMMMMMMMMMMMWX0kolccldkO0KKXNNNWWWWWWWWWWWWWWWWMMMMMMMMMMMWWWNNXXXXXKKXNNNWWN0l,;xNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWW0l:xXWMMWWWMMWMMMWWWKxlclc;xWWWWMWWWWWWN0kolc:coxO0KKXNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXXKKKKXNWXo,,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNk:c0WWWWMMMMMMMWWWXkocoxKNx:kWMWWMWWWXOoccloxOKKKKXNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKKKNO:'cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWKo:dXWWMMMMMMMMMWN0dclxKWWWNx;kWMWWWXOdccoOKXXNXXXNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWNXKKo':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc:kNMWMMMMMMMWWXkold0NWWMMWWk:kWWWKxllxOKNNXKKXXWMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNx,,dXNWMMWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMWWWMMMWWWWNNNNNNWWWWKl;oXWWWWMMWMMMN0dloOXWWMMWWWWWOcxNKxox0XXXKKKKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNo'':lldOKNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMWWMMWNXKKKkdooodkOKOc:kNWWWWWWWWN0xookKWWWWWWMMWWWWOcoxokKNXKKXNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMWWWNNNXK0Okkkxdddddddddddddddddddxo:'.;ddolcl0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMWWMNKxollcclcok0Okdol;;xNWWWMWWNKkoox0NWWWWWMWWWMWMWW0c:xKXKKXNWWMWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNK0kxdllcllllllllooddxdddddddxxxxxxdddl;,;cd0WWKxc:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMW0oclxOKKkloKWWWWWXxokKKXWWWX0xox0NWWMMMMMMMMMWWWWNOdd0XKKXWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWNNKkdolccloodkOKXXNNWWMMMWWWWMMMMMMMMMMMMMMMWNXkll0WWWNXO::0WWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMNx:lONWWWMWNNWWWWWWXKXN0dok0kdxOXWWWMMMMMMMMMMMWWW0cckXKKXWWMMMMMMMMMMMMMMMMMMMWWWWWWNXOkdolcclldxOKXNWWMMMMMMMMMMWWMMMWMMMMMMMMMMMMMMMMMWWNk:xNWWWNXd,lXWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMWMMWWk:dXWWWWMMMMMMMMWWWXXWWOlc;;o0NWMMWMMMMMMMMMMMMMWKc:0XKKNWMWWMMMMMMMMMMMMMMWWMMWNKkdllclodk0KKNWWWMWWWMMMMMMMMMMWWWWWWWMMMMMMMMMMMMMMMMMMWWO:ckXWWWNNOc:l0WWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMWWWNKc;kNWMWMMMMMMMMWMWNNNXKKKXOl:ckNMMWMMMMMMMMMMMMMWx:d0KXWMMMWWMMMMMMMMMMWWWWWX0xoc:ldk0KNWWWWWWWWWWWWWWMMMMMMMMMMWNNXKKNWWMMMWWWMMMMMMMWMWWWXOdcoKWWWNXKOl:kWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"WWWWKkocclxXWWWMMMMMMMMMWXKKKKXWWWXOOo,xWMMMMMMMMMMMMMMMNx:lONWMMMMMMMMMMMMMMMWNKOdlccoxOXWWWNNWWWWWWMMWWWMMMMMMMMMWWMN0xooxkxdkKXWWWWMMMMMMMMMMMMWWWXkclXWWNNNNKl:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"WWXxcld0XNWWWMMMMMMMMMMMNKKNWWWWWWX0Xk'oNMMMMMMMMMMMMMMMW0l;dNWWMMMMMWWWWWWWXOdlcldkKNWWXX0kddddkKWWMWWMMMMMMMMMWWMMW0dcokOXWNOddddONWWWWMMMMMMMMMWWMWXocOWWWNNNN0:cKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"WXd:xKKNWWMMMMMMMMMMMMMMMWWMMMMWWN0OOl:OWMMMMMMMMMMMMMMMMWk::kNWMMMMMWWWWNOdlldOKNWWWXOdooc:kK0o;xWWWWMMMMMMMMMMWWWWXocx0OKNWWWWN0cckXWMWWMMMMMMMMMMWNOclKWMMWWWN0c:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"Wx;dNX0NMMMMMMMMMMMMMMMMMMMMMMMWNO::cl0WMMMMMMMMMMMMMMMMWWKxc:xXWMMWMWWXkooxKNWWWWWNKdcd0KOONWNdl0WWMWMMMMMMMMMMMWWWWKxdlcOXKKXNNKOxcoKWWWMMMMMMMMMWWk:o0NWMMMMMN0l:oKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"Wd'xWX0XMMMMMMMMMMMMMMMMMMWWMWNK0kc:kNWMMMMMMMMMMMMMMMMMWNXX0o:lkKNWN0o:lONWWWWWWWXxoox0NWWWXkddONMWWWMMMMMMMMMMMMMWWMWN0llxdloOX0xolxXWMMMMMMMMWWMMWOcoXWWMMMMWWNKk:cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"W0c:kX0KNWMWWMMMMMMMMMMMWWWNX000X0cc0WMMMMMMMMMMMMMMMMMWWXOxk00xoodxd:;dKWMMMMMWWWKclOXWWWWNklkNWWMWWWMMMMMMMMMMMMMMMMWWN0xx00dododOXWWWMMMMMMMMWWMWWNd:OMMMMMMMMNNNd;xWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MWO:lKX0KNWWMMMMMMMMMMMWWNXK00XXOc:kWMMMMMMMMMMMMMMMMMMMWkldKWWWWNKxc:xXWWMMMMMMWWKll0WWWXkdxONWXKKNMWWMMMMMMMMMMMMMMMWXxc;cxXNXKXNWMWWMMMMMMMMMWWWWWOclKMMMMMMMWWNWO:oNMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"WWk:xNNKKKXNWMMMMMMWWNNXKkodkkoccoKWWWMMMMMMMMMMMMMMMMMWOcdXWWWWWWWNklONWWMMMMMMWW0clKNNXkokNWXx:,;lx0WWMMMMMMMMMMMMMMNx;,;,:ONWWMMWWWMMMMMMMMMMWWX0dcoKWMMMMMMMWNNNx;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"WWO:dXKxdOKKKXXXXNXKKK0KKd;:loxOXNWWWMMMMMMMMMMMMMMMMMMXooXWWMMWWWWWKooKNWWWMMMWWWNxlooodkKWMWk;,,,,'c0WWMMMMMMMMMMMMMXl,;;,;xNMMMMMMMMMMMMMMMWN0dold0NWMMMMMMMMWNXOl:ckWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMXdloc;lKNNXXXXOdxKNNNKd:lKWWWMMMMMMMMMMMMMMMMMMMMMMMWOcxNWMWMMWMMWWXxoxKWWWMWMMWWNKOO0XWMWMWk;',,'',kWWMMMMMMMMMMMMMXl,;;;:kNMMMMMMMMMMWWWWMWXocx0NMMMMMMMMMMMMWKKXKo;dNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"WWWWNXOccKWWWWWXo;cloolcoOXWWWWMMMMMMMMMMMMMMMMMMMMMMMWxckWMMMMMMMMWWMXolKWWWWWWWWWMMWMMMMWWMW0c'',,';OWWMMMMMWWWWWWWWXx:;;lkNMMMMMMMMMMMWWWMWW0coXWWWMMMMMMMMMMWWNKNMXo;kWWWMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"WWWMWMWOlloooooclk0OkO0XWMWWWWWMMMMMMMMMMMMMMMMMMMMMMMNdcONMMMMMMWMMMMXdo0NNWWMMMWMMMMMMMMMMMMW0l:;clxXWNWWWWNXKKKKXXNXXOk0XWWMMMMMMMMMMMMMWWW0ll0WWWMMMMMMMMMMWWMWKXWWO:oXWWWMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMWNKOkkkOKNWMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMNdlONWWWWMMMMMMMWXxoONWWMMWMMMMMMMMMMMMMMWN0OKNNX0Oxdolc::::;;:cdOXNNNWWWMMMMMMMMMMWNNKdcoKWWWWMWMMMMMMMMMWMWNKXNx;dNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMWWOcoKNNWWMMMMMMMMMNOddkKWMWWMMMMMMMMMMMMMWWNNKOxc:ccldkO0K000Okoc;ckXWWWWMMMMMMWWWWKdlld0NWMMWMMMMMMMMMMMWWMMWXX0:;0WWWMMWWWMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNOllokXWMMMMMMMMMWWNOol0WMMMMMMMMMMMMMMWWWNk:,:d0XWWWMMMMWMMMWWN0o,cKWWWWMWWMWWWXKx:oKNWWMMMMMMMMMMMMMMMMMMWWXXXo;xNWWWMWWWWMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMWWNx;:dKMMMMMMMMMWWMWWklONWWWMMMMMMMMMMMWMXo;d0XWWWWWMMMMMMWWMWWWWNo'oNMWWWWWWNXX0dlo0NNWWMMMMMMMMMMMMMMMMMMMWX0KKc:0WWWWNXXXWMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXNWWMWWW0dlcclkNWW0::0NWWMMMMMMMMWMMWWKdd0XKKXNWWWMMMMMMMWd'dNWWWMMMMMMMMMMMMMMWWWWO,lXWWWWWKxddddx0WWWWWMMMMMMMMMMMMMMMMMMMMWN0KNk:xXOdoddoco0NWWMMWWWWWWWMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWWMWMMWNOxoccllccldOOo:lk0Ol,lXWK::0NNWWMMMMMMMMMMMWWXkodxxdddkKNWNWWWWWocKWWWWMMMMMMMMMMMMMMWWWNd,l0XNNX0ook0KNWMMWWMMMMMMMMMMMMMMMMMMMMMMWNKKNO:cllkKXNXOc:ON0xdlllloox0NWWMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWWMWN0o:coxO0KXK0kc;';ONWWWNx;dNNd,oXWWWWMMMMMMMMMMMMWWK0OO0XKkdx0XKK0OxloOXNWWMMMMMMMMWWWWMMWNKx:lOkxxddxkKWWWWWMMWWMMMMMMMMMMMMMMMMMMMMMWWWKKNk;,c0WWWWWWk;;ccldkOkkkxl:cxXWMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWWW0l;lkXWWWWWWWWWNd'lXWWWWWXlcKWKo:lk0XWWWMMMMWMMWWMWWWWWMWWWWXOkkkO00KOlcodONWMMMMMMMWWWNX0xl;;dXWWNXKXNWWWWMMWMMMWMMMMMMMMMMMMMMMMMMMWWMMWXKkc:clKWWWWWW0;;xXWMWWWWMWW0o:c0WW\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWWO;:ONWWMMWWWWWWWWN0KNWWWWWNdlKWWN0d:;l0WMMWWMMMMMMMMMMMWWWMMMWWWWWMWWWWKxc;;lxO0KXXK0Okdl:::lkKNWWWX0XWMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:;oKkoKWWWWWWNKKNWWMMMMMMWWWN0:;OW\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWK::0WWMMMMMMMMMMWMMMWMWWWNKkccxOXWNk:lONMWWMWMMMMMMMMMMMMMMMMMMMMMMMMMWWWNK0kdolllllllllodk0XWWWWMWWKddKNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWNkc:lxxlxXWWWWWWWWMMMMMMMMMWWWWWk,lN\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWk,oNWWMMMMMMMMMMMMMMWMWN0l:ldxo:c0Nk;oNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWOo0WWWWNNNNNNNNWWWWWWMMWWMWWW0c;oxOOk0NWMMMMMMMMMMMMMMMMMMMMMMMMWWWWXKO:,lxddxkXWMWWMMMMMMMMMMWWWMM0:cK\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWO,cXWWMMMMMMMMMMMMWMMWKo:o0NWWW0::KKl;o0XNWWMMMMMMMMMMMMMMMMMMMMMMMMWNKxlxXMWWWWMMWWWWMWWMMMMMMWWWWW0c;dOxdxxONMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXKo':0WNXOc:xXWWMWMMMMMMMMMMMMW0:cX\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWXo,dNWWMMMMMMMMMMMWWNk:cOWWWWWWNo,dX0dlclco0WMMMMMMMMMMMMMMMMMMMWNKOkkdlxNWWWWWMMMMMMMWWWMMMMMWMWNKo;cOWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXX0;;kNWWWWXd;cOWWWMMMMMMMMMMWWWk'oN\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWWXl;dXWWWMMWWWMWWMWXd:dXWWMWMMWXl:ddddkd:;oKWMMMMMMMMMMMMMMMMMMMWWNXXNNOdx0KXWWWWMWWWWWWWWWWMWNXkl;ckNWWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWN0x:,lXWWWWWWW0c;xNWWWWWMMWMMWWW0::0W\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWWWXd;l0NWWWWMMWWWWXo:kNWMMMMWWWx:kWXOl::o0NWWMMMMMMMMMMMMMMMMMMMMMMMMWWWXOxdxxxk0KKKXXNNXXKOxdl:cdONWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0d:;;;:0WWWMWWWWXo,oXWMMWWWMMWWNO:;OWW\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMWWWWWNOl;lkKNWMMWWWXo;kWWMMMWMMW0cdNWWXc,xNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNKOxddooooddolllodkKNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc:,,ckkcdNWWMWWMWWNo,dNWWMMMWWWKd;c0WWM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMWWMWWWN0xl:cxKNWWNd;xNMWMMWWWWKclXWWWK:,xXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNWWMWWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWW0:,ccoKWNxckWWWWWMWWWXc;kNWWWWXkl:ckNWMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNKkl:cdKO;lXWWMWWWWW0ooKWWWWOoc:oOXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWKO00OkddKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNo,odOWWWXdcOWMWWWMWWW0::KNKxl:cd0NWWMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWKkxKo,kWWWWWWWXklxXWWWWXdx0d;,:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOkxdxkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWO:cOkkXWWWXdckWMWWWWMWNd;cl:cdKNWWWWMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMWMKc:OWWWWWN0do0NWWWWNOlOO::dOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWWMWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMW0c:kXXxkNWWWNdckNWMWWWWWk,,o0NWWWWWMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKl;xNWNN0o:oXWWWWWWXdd0l,xNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXkc:xXWWKdOWWWWNkco0NWWWWNo;kWWWMWMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWk;;llldxkxox0NWWWNklk0::0XWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxllco0NWWWWOxKWWWWWKo:lxOO0x;lXMWMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOxddOXWWWXxldKNN0ooXXc:0XXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,ckKNMWWMMXxkNWWWN0ocoxolcldKWMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWWWMWNKdlx0xo0WWk:lk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWO:lKWWWMWWMW0d0WNOoldKWWWWWWWWMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMW0dlckNWWN0occlONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNd;xWWMWWMMMWNxdkdlkXWWMWWMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKolXWWMWWW0c;dXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWN0o:dXWWMWWMWWWXOodOXWMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNOckWWWWMWWO;c0XNMMWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxo:l0NWWWMWWWWNkcoxo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNKdoXWWMMWWWNd;oKXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNo'cx0NMMWMMMWWWNd;c0KodNWMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXOlOWWMWMMMWWNkccodOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWKc;OWWWWWWWWWWW0l;dKWWOlOWMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXK0odXWWMWWWMMWWWN0xol:oXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWN0l;xXNNXXWWWWWKd;:kXWWWXodXMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKdl0WWMMMMWMMMMMMWWWKl;xXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMWWMWWX0Okkdl::xKXXNWWWWWXx::xKNWWWMW0okWMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXXOokWMMMMWMMMMMMMMMWWNOc:kKXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMWWMMWWWWWXo;clcox0KNWWWWWWWNOc;dKNWWWWWWMNxlKMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXOodNMMMMMMMMMMMMMMMMWWW0o:lkKXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMWWWWWWNXNNNXKkl:dKXNWWWWWMMWWWNkc;lOXWWMWWWWWWW0okWMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0doKWMMMMMMMMMMMMMMWWMMWWNOocldk0KXXXNNWWWWWMMMMMMMWWWWWWWWWWWWWWWNNXXXNWWWNNNOlcllllcloONMMMWMWWWWWWXxc;lOXWWWWMWMMMWWWNxoKWWMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXd::xNWMMMWMMMMMMMMMMMMMWMMWWWXkolcclxKXXXXXXNNNXNNNNXXXKXNXXXXXXNXOxxO00XNX0koc:lkOkO0KNWWWWWMMWWWWN0o::d0NWWMMMMMMMMMMWN0l;dNWWMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNx:ccoOXWMWWWMMMMMMMMMMMMMMMWWWWWNX0dccdxxddx0XNNNNNNNXOlokO0KK00kdl::loooollodkKXNWWWWWWWWMWWMWWN0dc:lkKNWWMMMMMMMMMMMWNx;colOWWWWMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWKooKXkoldOXWWWWWMMMMMMMMMMMMMMMMMWWMWXkdodooxO00OkkkOkxdxOxddoddddxk00Okkkkk0XXXNWWWWWWWWMMWWWWKkl:lxKNWMWWMMMMMMMMMMMMXo;oXXooXMMWMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNkl0WWWNKxoooxk0XNWWWWWMMMMMMMWMMMMMMMMMWWWMMWNNNXKKKKKKXWWWWXK0OkkxxddoooooooollloxOXWWWWWWNKkoccdKWWMMWMMMMMMMMMWMWWWKl;xXWWOlxNWWMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWKoxNMMWWWWWX0kdolodxOKXNWWMMWWMMMMMMMMMWWWWWWWWWWMMWWWWWX0OOkddxxkO0KKXXNNNNNNNNXKOdcckNNKOxolokKNWMWWMMMMMMMMMMMWWMWNOc:kXNWWNxcOWMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNxlKWWWWWWMWWMMWNXOkdollooddkOKXXNWWWWWWWWWWWWWMWWWWWWW0odO0KXNNWWMMMWWNNNNWWWWWWWWWW0:;ddodxOXWWMMMMMMMMMMMMMMMMMMWXOc;o0NWWWWWKllKWWMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNOlkWWMWMMMMMMMMMMMMMWNXXK0kdoooolloodddxxkkOOO0000KKKXOccONNXKK00OOkkxxxddddxxxk0XWNNKo:kXNWWWWMMMMMMMMMMWMMMMWWWWXx:;o0NWWWWWWMNkcxNMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNdlKWMWWMMMMMMMMMMMMMMWWWWMMMMWNNXK0OOkkkxxdddddddddxkOo:kNXOlokOOOOO00KXXXXKOkxo:lKWWNd:kWWMMMMMMMMMMMMMMWWMMWWNKx::dKNMWWWMMWWMWKlc0MMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx:dNWWWWMMMMMMMMWWMMMMMMWWMMMMMMMMMMMMMMMMMMMWWWWWWNWKkllKWNx:kWWWWWWWWWWWWWNNWWKc:0WWWk;oNMMMMMMMMMMMMMMMWWWWNOo:cxKWWWMWWWMMMWWMNkcdNMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWW0c;lddkOKNWMMWWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWM0o;oNWNo,OWWWMMMMMMMMMMMMWMNo:OWWW0;lNMMWWMMMMMMMMMMMWXOoccoONWWMWMMMMMMMMMWWWKlcOWMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNklkX0kxdoddk0NWWWWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWKxccKMWx,xWWMMMMMMMMMMMMMMWNd;OMWW0;cXMMMMMMWWWMMWNKkoccokXWWWWMMMMMMMMMMMMMWWNOcoXWWWMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWKldNWWWWNNKkdoodkOKNWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOlc0WWO;dWMMMMMMMMMMMMMMMMNo;OMWWKccKMMMWWWWWN0xlccldONMWWMMMMMMMMMMMMMMMMMWWWXdcxKKNWWWMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNxcOWMMMMMWWWWNKkxdooddkO0XNWMMMMMWWMMMMMMMMMMMMMMMMMWWWX0l:0MW0:lXMMMMMMMMMMMMMMWMXc;0WWW0:cXWWNK0kxooodk0XWWMMWWMMMMMMMMMMMMMMMMMWWWWWOc:cclkNWMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNN0clXMMMMMMWWMMMWWWNXKOkdoloooodxkOO0KKXXNNWWWWWWWMMMMWWWNXd,xWWNo;OWWMMMMMMMMMMMWWW0;cXWWNO:cxxxdddxk0XNWWWMMMMMMMMMMMMMMMMMMMMMMWWWWX0xdx0XKl;kWWMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKxlc:,xWMMMMMMMMMWWWWWWWWWWWNNXKOkxdollllllooooddddxxxkkkkkO0Od;oNWW0:cKWWWMMMMWWWWWWNKxcxXNNXdckXXXNWWWWMMMWWMMMMMMMMMMMMMMMWWWMMMWWX0kxdxOKXNWXd'cKMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOl;lol:oKNWWWWMMWWMMMMMMMWWMMWMMWWWWWNNXXXXKK000000000OOOOOO0K00dcONNXkcokkOOOOOOkkxdllloxKWWWKc:0WMWWWMMMMMMMMMMMMMMMMMMMMMMMWWWX0kxxxxk0NWWNX0xc,'lKMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:lKN0kxddxkOKXNWWWMMMMMMMWWMMMWWWMMMMMMWWMMMMMWWWMMMMMMMWWWWWMWO:oXWWN0kdooooooooodxk0XNWWWN0o,oXWMMMMMMMMMMMMMMMMMMMWWWWWNK0kxxxxkKXWWWWWNNKx::okOXWWMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMNk:oXWNNNNX0kxxddxxxkO0KXNWWWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNd;dNWWWWWWWWWWWWWWWWWNKOxdollokXWMMMMMMMMMMMMMMMMMWWX0kxdddxxk0XWWWWWWWNKkolclxKWWWWWWMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMW0l;dXNNWWWWMWWNXK0OkxddxxkxkkO0KXNNWMMMWWWMMMMMMMMMMMMMMMMMMMMMWWXdcllllodxxxxxxxxdollllldkOKNWWWWWMMMMMMMWWNNXKOkxddddxO0XNWWWWWWWWWXOdlccdOXWWWWWWMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkxxxkKNWMMMWWWWWWWWWNNNXK0kkxxxxxxxkkkkOO00KXNNNWWMMMMMMMWWMMWWWWXK0OOOkxdddddxxkOO0KXWMMWWMWWWNNNXK0OkxdooddddxO0XWWMMWWMWWWWWNKkoccokKNWWWWMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXOxdxxxOKWWMWWWWWMMWWWWWWWWWNXXXKK0OOkkkxxxxxxxkkkkOO0KKXXKXXXXKXXXXXXKKKKKKKK000OOOOOkkkxxdddddddddxkO0KNWWWWWWWWMMWWWWWNKOdlcldOXWWWWWWWWMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWN0xxdxdxO0XNWWWMWWWMMWWWWWWWWWWWWWWWWWWNNNXK0OOkkkkkxxxkkkkxxdolloooooodddxxddddddxkkO00KKXNWWWWWWWWMWWWMWWWWWWWNX0kdlcldOXWWWWWMWWMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWWWWNX0xdoolodxk0XNWWMMMWWWWMMWWWMMMMMMMWWMMMMMMMMMMMMMWWMWMWWNXNNNNNNNNWWWWWWWWWMMMMMWWWWWWWWWWWWWWWWWWNNNXK0kdolldx0XNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMWWWNXKOkdollcldxk0KXNWWWWWWWWWWMMWWWWWWWWWWMMMMMMMMMMWWWWWMMMMMWWMMMMWWWWWWWMMMMMMMWWWWWWNNNXXK0Okxdollodk0KNWWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWMWNX0OxdolccclloddxxxkOOO0KKKKKXXXXNNNNNNNNNNNNNNNWWNWWNNWNNNNNXXXXXKKK0OOkxxxddxddolloolodxOKXNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Okxddooc::::;coooollccccccccccccllcccodooollllllllcc::::cllllool;,oxkk0KKXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMWWWMMWWWWWNXXX0dcxNNNXXKKK0OOOkkkkkkkkkxdo;';oddxxxxxxxxxkOKXNNNWNx,lXWWWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMWWWWWNd:xNWWWWWWMMWWMMWMMWWMWWXd;;:cONWWWWWMMMMMMWWWWWKo;lKWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWWNd;oKWWWWWWWWWMMWWWWWNKx:'c00o:cx0XNWWWWMWWWNXOo:ckNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWNkc:dOKKXXNWWNNWNKOdc:loclKMWKxl::lodxdoooolc:'cKWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNX000ko:;;::cclllolcclokKW0loXWWWWNxcdxddddxxkOKOclXWWNXXXXNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xollccllllllcccc:,d00O0XNWMWW0cdNWMMMNxlKMMMWWWNNNN0ccxdoollcclooxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxc:ldk0KXXXXK0O0Okd:;d0KKKKKXNWWOcxWWWWMNdlKWXKK0OOOOOd;;lodxxxxddol:;lONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMXl,o0XXKK0000KKKKKKKKo:xKKKK000OKXkcxWMWWWXocO0kkkkO0KKXkcxXXXXKKKK00Oxo;;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWO,c0XXKKXXNWWWWWWWWWWK0NWWWWWNNNX0d:xWMMMMXl;xOkOKXWWWWWXKNWMMWWWMMWWN0x:'dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMW0;:0K0XWWWMMMMWWWWWWWWWWWWMWWWWWN0l'dNMWMMKc;O0OKWMWWMWWWMMMWMMWWWWNX0kl':0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNx,:x0XXNWWWWMMMWWWWMMMMMWWNNNXKxc,l0WWWWM0:;xOkOKXNNWWWWWWWNNNXX0OOxl:,c0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:;cx00KXXXXNNNNNNXXNNNX0Oxdl;;ckNWWWWWW0l;;;;::cldxxxxxxkkxoolc:;::lkXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWXkc::cclcccccccccccccc::cccokKNWWWWWMMMWWXKOkkkxolccccccclc:cldxOKNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNKkolc::;::ccclllllodk0NWWMWWMMMMMMMMMMMMWWWWWWWMWWWWNXXNWWWWMMMWWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"\r\n" + 
				"");
		
	}
		
	public static void main() {
		printSignature();
		printArt();

	}
		
	}

}
